### ISSUE TITLE
插件报错了

### ISSUE THREAD

**Issue by cnxiaodoubi** [BERADQ/koishi-plugin-genshinvoice-vits#11]
~~~ 
command gsvits 前进路上总是会历经无尽的艰难险阻
                        TypeError: Cannot read properties of undefined (reading '1')
                            at isay (/koishi/node_modules/koishi-plugin-genshinvoice-vits/lib/index.js:62:22)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Command.<anonymous> (/koishi/node_modules/koishi-plugin-genshinvoice-vits/lib/index.js:29:20)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1121:14)
                            at async Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1135:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2154:22
                            at async Proxy.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2057:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:860:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:860:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:860:16)
~~~

**Comment by idranme** [comment]
Duplicate of #10
